# -*- coding: utf-8 -*-
"""BT2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/maiphuctram/giaithuat_TD/blob/main/BT2.ipynb
"""

a = int(input('nhap a = '))
b = int(input('nhap b = '))

def uscln(a, b):
    if (b == 0):
        return a;
    return uscln(b, a % b);
print('UCLN cua',a,'va ',b,'la :',uscln(a,b))