# -*- coding: utf-8 -*-
"""BT3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/maiphuctram/giaithuat_TD/blob/main/BT3.ipynb
"""

n = int(input("Nhập số cần tính giai thừa: "))
 
def giaiThua(n):
    if n == 0:
        return 1
    return n * giaiThua(n - 1)
 
print (giaiThua(n))