# -*- coding: utf-8 -*-
"""BT08_CaiDatNganXep_Stack

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKhlKVhLQ4l9DE7zDGQuieS7gZ-W4lOq
"""

# sử dụng list 
stack = ['a']
# hàm append () để đẩy
# phần tử trong ngăn xếp
stack.append('b')
stack.append('c')
 
print('Ngăn xếp ban đầu')
print(stack)
 
# hàm pop () để bật lên
# phần tử từ ngăn xếp trong

print('\nCác phần tử xuất hiện từ ngăn xếp:')
print(stack.pop())
print('\nNgăn xếp sau khi các phần tử được bật lên:')
print(stack)