# -*- coding: utf-8 -*-
"""BT09_CaiDatHangDoi_Queue

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-A2Zkwn6OdHcHJumRpAha_WA4EBQwUY
"""

# Khởi tạo hàng đợi
queue = ['a']
 
# Thêm phần tử vào hàng đợi
queue.append('b')
queue.append('c')
queue.append('d')
 
print("Hàng đợi ban đầu")
print(queue)
# Xóa các phần tử khỏi hàng đợi
print("\nCác phần tử được xếp thứ tự từ hàng đợi")
print(queue.pop(0))
print(queue.pop(0))

print("\nHàng đợi sau khi loại bỏ các phần tử")
print(queue)
 
# In không chú thích (queue.pop (0)).
# sẽ tăng và IndexError.
# vì hàng đợi hiện đang trống.