# -*- coding: utf-8 -*-
"""BT12_CaiDatDoThiVoHuong

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1weBePiLOJYlo-6b1gIOCJiTmpJkQqKKG
"""

import networkx as nx
import matplotlib.pyplot as plt
g = nx.DiGraph()
g.add_nodes_from([1,2,3,4,5])
g.add_edge(1,2)
g.add_edge(4,2)
g.add_edge(3,5)
g.add_edge(2,3)
g.add_edge(2,5)
g.add_edge(1,4)
g.add_edge(3,4)

nx.draw(g,with_labels=True, arrows=False)
plt.draw()
plt.show()