# -*- coding: utf-8 -*-
"""BT16_SapXepNoiBot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkkK49N7KJNG15ztAaxMkHQ9UL1Av5_d
"""

def bubbleSort(arr):
    n = len(arr)
    # Traverse through all array elements
    for i in range(n):
        # Last i elements are already in place
        for j in range(0, n-i-1):
            # traverse the array from 0 to n-i-1
            # Swap if the element found is greater
            # than the next element
            if arr[j] > arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]
        print('Bước thứ',i+1,':',arr)
  
# Driver code to test above
arr = [64, 34, 12, 25, 90, 22, 11]
print('Mảng ban đầu:',arr)
bubbleSort(arr)
  
print ("Sorted array is:")
for i in range(len(arr)):
    print ("%d" %arr[i]),